### ISSUE TITLE
Description is empty

### ISSUE THREAD

**Issue by wanecek** [2opremio/ssweb#2]
In `./src/index.html.ejs`, the content of `<meta name="description">` is empty. This controls what is show in the summary on e.g. Google. IIRC it should be somewhere between 50-300 characters long.

This is what it can look like when you don't set it explicitly, and let google decide for you :joy:

![certus](https://user-images.githubusercontent.com/1533747/38470419-b35604b0-3b62-11e8-92c8-6ed3aa3167e7.png)

**Comment by 2opremio** [comment]
Interesting, I will come up with something. thanks!
